# Generated by Django 2.0.7 on 2019-11-23 13:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='checkIn',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 23, 13, 39, 41, 505420, tzinfo=utc)),
        ),
    ]
