# Generated by Django 2.0.7 on 2019-11-23 13:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_auto_20191123_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='checkIn',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
