# Generated by Django 2.0.7 on 2019-11-23 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_auto_20191123_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='checkIn',
            field=models.DateTimeField(default=django.utils.timezone.activate),
        ),
    ]
