# Generated by Django 2.0.7 on 2019-11-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_auto_20191123_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='checkIn',
            field=models.DateTimeField(default=None),
        ),
    ]
