# Generated by Django 2.0.7 on 2019-11-23 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_auto_20191123_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='checkIn',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
