# Generated by Django 2.2.7 on 2019-11-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0006_auto_20191123_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='hostContactNo',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitorContactNo',
            field=models.CharField(max_length=13),
        ),
    ]
